name: chall2026-interns-portal

services:
  interns-portal:
    image: athack-ctf/chall2026-interns-portal:latest
    container_name: chall2026-interns-portal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2026:8000"